version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10  # або інша версія Python, яку ти використовуєш
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt || pip install pytest
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest  # або pytest tests/ — якщо у тебе окрема папка tests/
workflows:
  version: 2
  test-workflow:
    jobs:
      - test
